version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/ci"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
