builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
    files:
      - LICENSE
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  use: github-native
