name: docker-tests
on:
  pull_request:
    branches:
      - main
    paths:
      - Dockerfile
jobs:
  test-root-dockerfile:
    name: test root dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5

      - name: test Dockerfile
        uses: fsouza/docker-publish-action@v1.0.1
        with:
          docker-image: fsouza/s3-upload-proxy
          skip-push: true
