name: docker-tests
on:
  pull_request:
    branches:
      - main
jobs:
  test-dockerfile:
    name: test-dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: setup qemu
        uses: docker/setup-qemu-action@v2.2.0

      - name: setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.6.0

      - name: build
        uses: docker/build-push-action@v4.1.0
        with:
          cache-from: fsouzaci/gha-cache:s3-upload-proxy
          context: .
          push: false
          tags: fsouza/s3-upload-proxy:latest
          platforms: linux/amd64,linux/arm64
