name: docker-push
on: create

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        if: github.event.ref_type == 'tag'

      - uses: actions/setup-go@v2.1.4
        if: github.event.ref_type == 'tag'
        id: go
        with:
          go-version: 1.17

      - name: go-build
        if: github.event.ref_type == 'tag'
        run: go build -o s3-upload-proxy -mod readonly
        env:
          CGO_ENABLED: 0

      - name: docker-publish
        if: github.event.ref_type == 'tag'
        uses: fsouza/docker-publish-action@v1.0.1
        with:
          dockerfile: ci/Dockerfile
          docker-image: fsouza/s3-upload-proxy
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
