name: goreleaser-test
on:
  push:
    branches:
      - main
    paths:
      - .goreleaser.yml
  pull_request:
    paths:
      - .goreleaser.yml
jobs:
  test-goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: docker://goreleaser/goreleaser
        with:
          args: release --snapshot -f ci/.goreleaser.yml
