name: ko-build
on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6

      - name: docker meta
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: fsouza/s3-upload-proxy
          sep-tags: ","
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: login to docker hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/setup-go@v5.0.1
        id: setup-go
        with:
          go-version: "1.22.0"

      - uses: ko-build/setup-ko@v0.6

      - name: ko build
        run: |
          ko build --platform=all --bare --tags="$(echo "${RAW_TAGS}" | sed -e 's;fsouza/s3-upload-proxy:;;g')"
        env:
          KO_DEFAULTBASEIMAGE: fsouza/alpine-base
          KO_DOCKER_REPO: fsouza/s3-upload-proxy
          RAW_TAGS: ${{ steps.meta.outputs.tags }}
