name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        id: go
        with:
          go-version: 1.x

      - uses: actions/checkout@v2.3.3

      - name: install deps
        run: go mod download

      - name: run-tests
        run: go test -race -vet all -mod readonly ./...
        env:
          GOPROXY: off

  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.3
      - uses: golangci/golangci-lint-action@v2.3.0

  build:
    name: build-and-publish
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
    steps:
      - uses: actions/checkout@v2.3.3

      - uses: actions/setup-go@v2.1.3
        id: go
        with:
          go-version: 1.x

      - name: go-build
        run: go build -o s3-upload-proxy -mod readonly
        env:
          CGO_ENABLED: 0

      - name: docker-publish
        uses: docker://docker
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
        with:
          entrypoint: sh
          args: ci/docker-build.sh
