name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.5
        id: go
        with:
          go-version: 1.17

      - uses: actions/checkout@v2.4.0

      - name: run-tests
        run: go test -race -vet all ./...

  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - uses: golangci/golangci-lint-action@v2.5.2

  staticcheck:
    name: staticcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.5
        id: go
        with:
          stable: false
          go-version: 1.17

      - run: |
          go install honnef.co/go/tools/cmd/staticcheck@master

      - name: get staticcheck version
        id: get-staticcheck-version
        run: |
          echo "::set-output name=version::$(staticcheck --version | sed -e 's/,//g')"

      - name: staticcheck cache
        id: staticcheck-cache
        uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/staticcheck
          key: "${{ steps.get-staticcheck-version.outputs.version }}"

      - uses: actions/checkout@v2.4.0

      - name: run staticcheck
        run: |
          staticcheck ./...
