name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.0.3
        id: go
        with:
          go-version: 1.x

      - uses: actions/checkout@v2.3.1

      - name: install deps
        run: |
          go mod download
          (
            cd /tmp
            env GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          )

      - name: run-tests
        run: go test -race -vet all -mod readonly ./...
        env:
          GOPROXY: off

      - name: run-linter
        run: golangci-lint run
        env:
          GOPROXY: off
          GOFLAGS: -mod=readonly

  build:
    name: build-and-publish
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@v2.3.1

      - uses: actions/setup-go@v2.0.3
        id: go
        with:
          go-version: 1.x

      - name: go-build
        run: go build -o s3-upload-proxy -mod readonly
        env:
          CGO_ENABLED: 0

      - name: docker-publish
        uses: docker://docker
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
        with:
          entrypoint: sh
          args: ci/docker-build.sh
