name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        id: go
        with:
          go-version: 1.16

      - uses: actions/checkout@v2.3.4

      - name: run-tests
        run: go test -race -vet all ./...

  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: golangci/golangci-lint-action@v2.5.2

  staticcheck:
    name: staticcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        id: go
        with:
          stable: false
          go-version: 1.16

      - run: |
          go install honnef.co/go/tools/cmd/staticcheck@master

      - name: get staticcheck version
        id: get-staticcheck-version
        run: |
          echo "::set-output name=version::$(staticcheck --version | sed -e 's/,//g')"

      - name: staticcheck cache
        id: staticcheck-cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/staticcheck
          key: "${{ steps.get-staticcheck-version.outputs.version }}"

      - uses: actions/checkout@v2.3.4

      - name: run staticcheck
        run: |
          staticcheck ./...

  build:
    name: build-and-publish
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
      - staticcheck
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-go@v2.1.3
        id: go
        with:
          go-version: 1.16

      - name: go-build
        run: go build -o s3-upload-proxy -mod readonly
        env:
          CGO_ENABLED: 0

      - name: docker-publish
        uses: docker://docker
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
        with:
          entrypoint: sh
          args: ci/docker-build.sh
