name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - uses: actions/setup-go@v4.1.0
        with:
          go-version: "1.21"

      - name: run-tests
        run: go test -race -vet all ./...

  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3

      - uses: golangci/golangci-lint-action@v3

  staticcheck:
    name: staticcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - uses: actions/setup-go@v4.1.0
        id: setup-go
        with:
          go-version: "1.21"

      - run: |
          go install honnef.co/go/tools/cmd/staticcheck@master

      - name: get staticcheck version
        id: get-staticcheck-version
        run: |
          echo "version=$(staticcheck --version | sed -e 's/,//g')" >>${GITHUB_OUTPUT}

      - name: staticcheck cache
        id: staticcheck-cache
        uses: actions/cache@v3.3.1
        with:
          path: ~/.cache/staticcheck
          key: "${{ steps.get-staticcheck-version.outputs.version }}-${{ steps.setup-go.outputs.go-version }}"

      - name: run staticcheck
        run: |
          staticcheck ./...
