name: Build
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  lint-and-test:
    strategy:
      matrix:
        go_version:
          - 1.13
          - 1.14
        os:
          - macos
          - ubuntu

    name: lint-and-test (${{ matrix.os }}/go-${{ matrix.go_version }})
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/setup-go@master
        id: go
        with:
          stable: false
          go-version: ${{ matrix.go_version }}

      - uses: actions/checkout@master

      - name: install deps
        run: |
          go mod download
          (
            cd /tmp
            env GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          )

      - name: run-tests
        run: go test -race -vet all -mod readonly ./...
        env:
          GOPROXY: off

      - name: run-linter
        run: golangci-lint run
        env:
          GOPROXY: off
          GOFLAGS: -mod=readonly

  build:
    name: build-and-publish
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-go@master
        id: go
        with:
          go-version: 1.x

      - name: go-build
        run: go build -o s3-upload-proxy -mod readonly
        env:
          CGO_ENABLED: 0

      - name: docker-publish
        uses: docker://docker
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
        with:
          entrypoint: sh
          args: ci/docker-build.sh
