name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-go@v5.0.0
        with:
          go-version: "1.22.0-rc.1"

      - name: run-tests
        run: go test -race -vet all ./...

  staticcheck:
    name: staticcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-go@v5.0.0
        id: setup-go
        with:
          go-version: "1.22.0-rc.1"

      - run: |
          go install honnef.co/go/tools/cmd/staticcheck@master

      - name: get staticcheck version
        id: get-staticcheck-version
        run: |
          echo "version=$(staticcheck --version | sed -e 's/,//g')" >>${GITHUB_OUTPUT}

      - name: staticcheck cache
        id: staticcheck-cache
        uses: actions/cache@v3.3.2
        with:
          path: ~/.cache/staticcheck
          key: "${{ steps.get-staticcheck-version.outputs.version }}-${{ steps.setup-go.outputs.go-version }}"

      - name: run staticcheck
        run: |
          staticcheck ./...
